AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable


Naming/MethodParameterName:
  Enabled: false
Layout/LineLength:
  Max: 160
Style/FormatString:
  EnforcedStyle: sprintf
Style/FormatStringToken:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Metrics/MethodLength:
  Max: 15
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Metrics/AbcSize:
  Max: 30
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'Gemfile'
    - 'Guardfile'
    - 'config/routes.rb'
    - 'config/routes/**/*.rb'
    - '*.gemspec'
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/PerceivedComplexity:
  Max: 15
Style/GlobalVars:
  Exclude:
    - 'test/test_helper.rb'
Lint/MissingSuper:
  Exclude:
    - 'test/test_helper.rb'
Style/MissingRespondToMissing:
  Exclude:
    - 'test/test_helper.rb'
Style/TernaryParentheses:
  Enabled: false
Style/BlockDelimiters:
  AutoCorrect: false
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Style/RedundantSelfAssignment:
  Enabled: false
